description       "Configures apt and apt services"
recipe            "apt::default", "Runs apt-get update during compile phase and sets up preseed directories"
recipe            "apt::cacher", "Set up an APT cache"
recipe            "apt::proxy", "Set up an APT proxy"
recipe            "apt::update", "Update all out of date apt packages"
recipe            "apt::autoremove", "Remove any unused apt packages"
